# Site settings
title:       Droidict
email:       shekarrex@gmail.com
author:      Shekar
description: "Android technical blog"
baseurl:     ""
url:         "http://shekar.xyz"
date_format: "%b %-d, %Y"
twitter_username: shekarrex


#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Shekar
      layout: "post"
      category:  Android

  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"


# Google services
google_analytics:
google_verification:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: shekarrex
bitbucket_username:
stackoverflow_id:
twitter_username: shekarrex
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:title
paginate:     4
sass:
  compressed: true

port: 3000
